default:
  type: 'mysql'
  host: "localhost"
  port: 3306
  username: "demo"
  password: "demo"
  database: "demo"
  synchronize: true
  logging: true
  entities:
    - ./build/entity/*.ts
cli:
  entitiesDir: build/entity